# Spring profiles
spring.profiles.active=population, local

# Logger settings
log.level=INFO

# Access logs settings
accessLog.traceRequestBody=true
accessLog.traceResponseBody=true
accessLog.traceSentBody=true
accessLog.traceReceivedBody=true
accessLog.printErrorStack=true

# DB
db.driverClassName=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/demo
db.userName=postgres
db.password=postgres
db.maximumPoolSize=10
db.minimumIdle=5
db.idleTimeout=300000
db.connectionTimeout=20000
db.engine=POSTGRESQL

# Hibernate settings
hibernate.showSql=false
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect